/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.fooddeliverysystem;

import java.awt.BorderLayout;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author USER
 */
public class CustomerComplaintsPanel extends javax.swing.JPanel {
    private DefaultListModel<String> complaintsModel;
    private JList<String> complaintsList;
    /**
     * Creates new form CustomerComplaintsPanel
     */
    public CustomerComplaintsPanel() {
        initComponents();
        setLayout(new BorderLayout());

        // Complaints list
        complaintsModel = new DefaultListModel<>();
        complaintsModel.addElement("Complaint 1: Late delivery");
        complaintsModel.addElement("Complaint 2: Item damaged");
        complaintsList = new JList<>(complaintsModel);
        add(new JScrollPane(complaintsList), BorderLayout.CENTER);

        // Reply area
        JPanel replyPanel = new JPanel(new BorderLayout());
        JTextArea replyTextArea = new JTextArea();
        replyPanel.add(new JLabel("Reply:"), BorderLayout.NORTH);
        replyPanel.add(new JScrollPane(replyTextArea), BorderLayout.CENTER);
        JButton sendButton = new JButton("Send Reply");
        replyPanel.add(sendButton, BorderLayout.SOUTH);
        add(replyPanel, BorderLayout.SOUTH);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
