/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.fooddeliverysystem;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

/**
 *
 * @author USER
 */
public class DeliveryRunnerPerformance extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryRunnerPerformance
     */
    public DeliveryRunnerPerformance() {
        initComponents();
        setLayout(new BorderLayout());

        // Title
        JLabel titleLabel = new JLabel("Delivery Runner Performance", SwingConstants.CENTER);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 24));
        add(titleLabel, BorderLayout.NORTH);

        // Statistics
        JPanel statsPanel = new JPanel(new GridLayout(3, 1, 10, 10));
        statsPanel.add(createStatPanel("Top On-Time Deliveries", "Runner A: 50 deliveries"));
        statsPanel.add(createStatPanel("Top Hardworking Runners", "Runner B: 120 hours"));
        statsPanel.add(createStatPanel("Overall Performance", "Runner C: 98% rating"));
        add(statsPanel, BorderLayout.CENTER);
    }
    
    private JPanel createStatPanel(String title, String content) {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());
        JLabel titleLabel = new JLabel(title, SwingConstants.LEFT);
        titleLabel.setFont(new Font("Arial", Font.BOLD, 16));
        JLabel contentLabel = new JLabel(content, SwingConstants.LEFT);
        contentLabel.setFont(new Font("Arial", Font.PLAIN, 14));
        panel.add(titleLabel, BorderLayout.NORTH);
        panel.add(contentLabel, BorderLayout.CENTER);
        return panel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
