package com.mycompany.fooddeliverysystem;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GridBagLayout;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;

public class RunnerMain extends javax.swing.JFrame {
    ProfilePanel p1;
    ViewTaskPanel p2;
    RunnerTaskAccepted p3;
    TaskHistory p4;
    RevenueDashboard p5;
    CardLayout cardLayout = new CardLayout(); 
    GridBagLayout layout = new GridBagLayout();
    private String RunnerName;
    
    public RunnerMain(String RunnerName) {
        initComponents();
        this.RunnerName = RunnerName;
        lblNameRunner.setText("Welcome, " + RunnerName);
        // Apply custom font to jLabel1
        try {
            File fontFile = new File("src/main/resources/Font/Merienda-Black.ttf");
            Font customFont = Font.createFont(Font.TRUETYPE_FONT, fontFile).deriveFont(24f); // Font size 24
            lblNameRunner.setFont(customFont);
            TitleLbl.setFont(customFont);

        } catch (FontFormatException | IOException e) {
            e.printStackTrace();
            lblNameRunner.setText("Failed to load custom font."); // Display an error message if font fails to load
        }

        setTitle("Delivery Runner Panel");
        setSize(1500, 700);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        
        panelbg.setOpaque(true);
        panelbg.setBackground(new Color(255, 255, 255, 150));

        
        
        p1 = new ProfilePanel(RunnerName);
        p2 = new ViewTaskPanel(RunnerName, p3);
        p3 = new RunnerTaskAccepted(RunnerName, p4, p5);
        p4 = new TaskHistory(RunnerName);
        p5 = new RevenueDashboard(RunnerName);
        contentPanel.setLayout(cardLayout);
        contentPanel.add(p1, "Profile");
        contentPanel.add(p2, "ViewTasks");
        contentPanel.add(p3, "RunnerTaskAccepted");
        contentPanel.add(p4, "TaskHistory");
        contentPanel.add(p5, "RevenueDashboard");
        
        showProfilePanel();
       
    }
   
    private void showProfilePanel() {
        TitleLbl.setText("Profile");  // Set title when ProfilePanel is displayed
        cardLayout.show(contentPanel, "Profile");  // Show Profile Panel
    }

    // Method to switch to ViewTask Panel
    private void showViewTaskPanel() {
        TitleLbl.setText("View Tasks");  // Set title when ViewTaskPanel is displayed
        cardLayout.show(contentPanel, "ViewTasks");  // Show ViewTask Panel
    }
    
    private void showViewTaskAccepted() {
        TitleLbl.setText("Task Accepted");  // Set title when ViewTaskPanel is displayed
        cardLayout.show(contentPanel, "RunnerTaskAccepted");  // Show ViewTask Panel
    }
    
    private void showTaskHistory() {
        TitleLbl.setText("Task History");  // Set title when ViewTaskPanel is displayed
        cardLayout.show(contentPanel, "TaskHistory");  // Show ViewTask Panel
    }
    
    private void showRevenueDashboard() {
        TitleLbl.setText("Revenue Dashboard");  // Set title when ViewTaskPanel is displayed
        cardLayout.show(contentPanel, "RevenueDashboard");  // Show ViewTask Panel
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        btnTaskAccepted = new javax.swing.JButton();
        btnRevenueDashboard = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        btnTaskHistory = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnViewTask = new javax.swing.JButton();
        profilebtn = new javax.swing.JButton();
        panelbg = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        lblNameRunner = new javax.swing.JLabel();
        TitleLbl = new javax.swing.JLabel();
        logoutbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 700));
        setSize(new java.awt.Dimension(1500, 700));
        getContentPane().setLayout(null);

        MenuPanel.setBackground(new java.awt.Color(145, 189, 218));
        MenuPanel.setMaximumSize(new java.awt.Dimension(270, 700));
        MenuPanel.setMinimumSize(new java.awt.Dimension(270, 700));
        MenuPanel.setPreferredSize(new java.awt.Dimension(270, 700));

        btnTaskAccepted.setBackground(new java.awt.Color(174, 211, 236));
        btnTaskAccepted.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnTaskAccepted.setText("Task Accepted");
        btnTaskAccepted.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTaskAccepted.setOpaque(true);
        btnTaskAccepted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaskAcceptedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaskAcceptedMouseExited(evt);
            }
        });
        btnTaskAccepted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskAcceptedActionPerformed(evt);
            }
        });

        btnRevenueDashboard.setBackground(new java.awt.Color(174, 211, 236));
        btnRevenueDashboard.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnRevenueDashboard.setText("Revenue Dashboard");
        btnRevenueDashboard.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRevenueDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRevenueDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRevenueDashboardMouseExited(evt);
            }
        });
        btnRevenueDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevenueDashboardActionPerformed(evt);
            }
        });

        jButton12.setText("Exit");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btnTaskHistory.setBackground(new java.awt.Color(174, 211, 236));
        btnTaskHistory.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnTaskHistory.setText("Task History");
        btnTaskHistory.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTaskHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaskHistoryMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaskHistoryMouseExited(evt);
            }
        });
        btnTaskHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaskHistoryActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pic/apu.png"))); // NOI18N

        btnViewTask.setBackground(new java.awt.Color(174, 211, 236));
        btnViewTask.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnViewTask.setText("View Task");
        btnViewTask.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewTask.setOpaque(true);
        btnViewTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewTaskMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewTaskMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewTaskMouseExited(evt);
            }
        });
        btnViewTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTaskActionPerformed(evt);
            }
        });

        profilebtn.setBackground(new java.awt.Color(174, 211, 236));
        profilebtn.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        profilebtn.setText("Profile");
        profilebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        profilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilebtnMouseExited(evt);
            }
        });
        profilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profilebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnRevenueDashboard, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(profilebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaskHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaskAccepted, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewTask, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaskAccepted, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaskHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRevenueDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profilebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jButton12)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        getContentPane().add(MenuPanel);
        MenuPanel.setBounds(0, 0, 270, 700);

        panelbg.setBackground(new java.awt.Color(255, 255, 255));
        panelbg.setPreferredSize(new java.awt.Dimension(1430, 700));
        panelbg.setRequestFocusEnabled(false);

        contentPanel.setLayout(new java.awt.GridBagLayout());

        lblNameRunner.setFont(lblNameRunner.getFont().deriveFont(lblNameRunner.getFont().getSize()+8f));

        TitleLbl.setBackground(new java.awt.Color(145, 189, 218));
        TitleLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        TitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLbl.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TitleLbl.setOpaque(true);

        logoutbtn.setText("Logout");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbgLayout = new javax.swing.GroupLayout(panelbg);
        panelbg.setLayout(panelbgLayout);
        panelbgLayout.setHorizontalGroup(
            panelbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbgLayout.createSequentialGroup()
                .addGroup(panelbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbgLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblNameRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(660, 660, 660)
                        .addComponent(logoutbtn))
                    .addGroup(panelbgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelbgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        panelbgLayout.setVerticalGroup(
            panelbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbgLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelbgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNameRunner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoutbtn))
                .addGap(18, 18, 18)
                .addComponent(TitleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(panelbg);
        panelbg.setBounds(270, 0, 1430, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevenueDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevenueDashboardMouseEntered
        btnRevenueDashboard.setBackground(new Color(195,221,239));
    }//GEN-LAST:event_btnRevenueDashboardMouseEntered

    private void btnRevenueDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRevenueDashboardMouseExited
        btnRevenueDashboard.setBackground(new Color(174,211,236));
    }//GEN-LAST:event_btnRevenueDashboardMouseExited

    private void btnTaskAcceptedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskAcceptedMouseEntered
        btnTaskAccepted.setBackground(new Color(195,221,239));
    }//GEN-LAST:event_btnTaskAcceptedMouseEntered

    private void btnTaskAcceptedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskAcceptedMouseExited
        btnTaskAccepted.setBackground(new Color(174,211,236));
    }//GEN-LAST:event_btnTaskAcceptedMouseExited

    private void btnTaskHistoryMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskHistoryMouseEntered
        btnTaskHistory.setBackground(new Color(195,221,239));
    }//GEN-LAST:event_btnTaskHistoryMouseEntered

    private void btnTaskHistoryMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskHistoryMouseExited
        btnTaskHistory.setBackground(new Color(174,211,236));
    }//GEN-LAST:event_btnTaskHistoryMouseExited

    private void btnViewTaskMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTaskMouseEntered
        btnViewTask.setBackground(new Color(195,221,239));
    }//GEN-LAST:event_btnViewTaskMouseEntered

    private void btnViewTaskMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTaskMouseExited
        btnViewTask.setBackground(new Color(174,211,236));
    }//GEN-LAST:event_btnViewTaskMouseExited

    private void btnViewTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewTaskMouseClicked
        //RunnerViewTask viewTaskFrame = new RunnerViewTask(username);
        //viewTaskFrame.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btnViewTaskMouseClicked

    private void profilebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnMouseEntered
        profilebtn.setBackground(new Color(195,221,239));
    }//GEN-LAST:event_profilebtnMouseEntered

    private void profilebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnMouseExited
        profilebtn.setBackground(new Color(174,211,236));
    }//GEN-LAST:event_profilebtnMouseExited

    private void profilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profilebtnActionPerformed

        showProfilePanel(); 
    }//GEN-LAST:event_profilebtnActionPerformed

    private void btnViewTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTaskActionPerformed
        p2.reloadOrders();
        showViewTaskPanel(); 
    }//GEN-LAST:event_btnViewTaskActionPerformed

    private void btnTaskAcceptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskAcceptedActionPerformed
        p3.reloadOrders(); // Refresh data
        showViewTaskAccepted();
    }//GEN-LAST:event_btnTaskAcceptedActionPerformed

    private void btnTaskHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaskHistoryActionPerformed
        p4.refreshTable();
        showTaskHistory();
    }//GEN-LAST:event_btnTaskHistoryActionPerformed

    private void btnRevenueDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevenueDashboardActionPerformed
        p5.reloadRevenue();
        showRevenueDashboard();
    }//GEN-LAST:event_btnRevenueDashboardActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        //initialize login page
        dispose();
        // Open the login page
        new LoginPage(); // Replace this with the actual class name for your login page
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        //exit system
        JOptionPane.showMessageDialog(this,"Thank you for using the system!! Have a good day!!!!");
        java.lang.System.exit(0);
    }//GEN-LAST:event_jButton12ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RunnerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() { 
            public void run() { 
                new RunnerMain("c").setVisible(true); } });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel TitleLbl;
    private javax.swing.JButton btnRevenueDashboard;
    private javax.swing.JButton btnTaskAccepted;
    private javax.swing.JButton btnTaskHistory;
    private javax.swing.JButton btnViewTask;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNameRunner;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JPanel panelbg;
    private javax.swing.JButton profilebtn;
    // End of variables declaration//GEN-END:variables

}